[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd backend && npm ci --omit=dev"]

[phases.build]
cmds = ["cd backend && npm run build --if-present"]

[start]
cmd = "cd backend && node server.js"
